baseURL = "https://rsongphon.github.io/"
#relativeURLs = true
languageCode = 'en-us'
title = 'Satellite-Based AGB/CHM Estimation Model​'


# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
themeVariant = "relearn-dark"